// Curated Indian dishes: one serving as a gram breakdown of ingredient keys
// from food_manifest.json (grams are as-purchased weights: raw dal/rice/atta
// unless the key says cooked). Macros, diet_pref, suitable_for and allergens
// are computed from the ingredients by scripts/seed/dishes.js — never typed in.
// These are typical home-recipe proportions (curated estimates, not lab data).
//
// Row: [slug, name, meal slots (B=breakfast L=lunch S=snack D=dinner), prep minutes, cuisine, { ingredient: grams }]

module.exports = [
  // ---------------------------------------------------------------- breakfast
  ['poha', 'Kanda Poha', 'BS', 20, 'west', { poha: 60, onion: 30, potato: 40, peanuts: 10, oil: 7, green_chilli: 3, lemon: 5, turmeric: 1, coriander: 3, mustard_seeds: 1 }],
  ['jain-poha', 'Jain Poha (peas & peanuts)', 'BS', 20, 'west', { poha: 60, peanuts: 15, green_peas: 20, oil: 7, green_chilli: 3, lemon: 5, turmeric: 1, coriander: 3 }],
  ['upma', 'Rava Upma', 'B', 20, 'south', { rava: 60, onion: 25, oil: 8, urad_dal: 3, carrot: 20, green_peas: 15, green_chilli: 3, mustard_seeds: 1 }],
  ['jain-rava-upma', 'Jain Vegetable Rava Upma', 'B', 20, 'south', { rava: 60, beans: 20, capsicum: 20, green_peas: 15, oil: 8, mustard_seeds: 1, green_chilli: 3 }],
  ['idli-sambar', 'Idli Sambar (3 idli)', 'B', 30, 'south', { rice_raw: 60, urad_dal: 20, toor_dal: 20, drumstick: 20, tomato: 20, onion: 15, tamarind: 5, oil: 5 }],
  ['idli-chutney', 'Idli with Coconut Chutney', 'B', 25, 'south', { rice_raw: 60, urad_dal: 20, coconut: 25, chana_dal: 8, green_chilli: 2 }],
  ['plain-dosa', 'Plain Dosa with Chutney', 'BD', 25, 'south', { rice_raw: 60, urad_dal: 20, oil: 8, coconut: 20, chana_dal: 5, green_chilli: 2 }],
  ['masala-dosa', 'Masala Dosa', 'BL', 35, 'south', { rice_raw: 60, urad_dal: 20, potato: 80, onion: 20, oil: 12, mustard_seeds: 1, turmeric: 1, coconut: 15 }],
  ['rava-dosa', 'Rava Dosa', 'B', 25, 'south', { rava: 40, rice_flour: 20, maida: 10, onion: 15, oil: 10, green_chilli: 2, cumin: 1 }],
  ['uttapam', 'Onion Tomato Uttapam', 'BD', 25, 'south', { rice_raw: 60, urad_dal: 20, onion: 30, tomato: 30, capsicum: 20, oil: 8 }],
  ['pesarattu', 'Pesarattu (moong dosa)', 'B', 25, 'south', { moong_dal: 70, ginger: 5, green_chilli: 3, onion: 20, oil: 7 }],
  ['medu-vada-sambar', 'Medu Vada with Sambar', 'BS', 35, 'south', { urad_dal: 60, oil: 15, toor_dal: 20, tomato: 20, drumstick: 20, tamarind: 5 }],
  ['pongal', 'Ven Pongal', 'B', 30, 'south', { rice_raw: 50, moong_dal: 25, ghee: 10, black_pepper: 1, cumin: 1, cashews: 5 }],
  ['appam-stew', 'Appam with Vegetable Stew', 'BD', 40, 'south', { rice_raw: 70, coconut: 20, coconut_milk: 60, potato: 50, carrot: 30, green_peas: 15, coconut_oil: 5 }],
  ['puttu-kadala', 'Puttu with Kadala Curry', 'B', 40, 'south', { rice_flour: 70, coconut: 20, chana_dal: 40, onion: 20, coconut_oil: 5 }],
  ['ragi-dosa', 'Ragi Dosa', 'B', 20, 'south', { ragi: 50, rice_flour: 20, onion: 20, oil: 6 }],
  ['ragi-malt', 'Ragi Malt', 'BS', 10, 'south', { ragi: 30, milk: 200, jaggery: 10 }],
  ['aloo-paratha', 'Aloo Paratha with Curd', 'BL', 30, 'north', { atta: 70, potato: 80, ghee: 8, curd: 50, green_chilli: 2, coriander: 3 }],
  ['paneer-paratha', 'Paneer Paratha', 'BL', 30, 'north', { atta: 70, paneer: 50, ghee: 7, onion: 15, green_chilli: 2, coriander: 3 }],
  ['gobi-paratha', 'Gobi Paratha', 'B', 30, 'north', { atta: 70, cauliflower: 70, oil: 7, ginger: 3, green_chilli: 2 }],
  ['methi-thepla', 'Methi Thepla', 'BS', 25, 'west', { atta: 60, besan: 10, methi: 30, curd: 20, oil: 8, turmeric: 1, sesame: 3 }],
  ['besan-chilla', 'Besan Chilla', 'BS', 15, 'north', { besan: 60, onion: 25, tomato: 25, green_chilli: 3, coriander: 3, oil: 6 }],
  ['jain-besan-chilla', 'Jain Besan Chilla', 'B', 15, 'north', { besan: 60, tomato: 25, capsicum: 20, green_chilli: 2, coriander: 3, oil: 6 }],
  ['moong-chilla-paneer', 'Moong Dal Chilla with Paneer', 'B', 20, 'north', { moong_dal: 60, paneer: 30, onion: 20, oil: 6, green_chilli: 2 }],
  ['masala-oats', 'Masala Oats', 'B', 15, 'modern', { oats: 50, onion: 20, tomato: 25, carrot: 20, green_peas: 15, oil: 5 }],
  ['oats-porridge', 'Oats Porridge with Banana & Almonds', 'B', 10, 'modern', { oats: 50, milk: 200, banana: 60, almonds: 8, jaggery: 8 }],
  ['overnight-oats', 'Overnight Oats with Chia & Berries', 'B', 5, 'modern', { oats: 50, greek_yogurt: 100, milk: 100, chia: 10, strawberries: 50 }],
  ['sabudana-khichdi', 'Sabudana Khichdi', 'B', 25, 'west', { sabudana: 70, roasted_peanuts: 20, potato: 50, ghee: 8, green_chilli: 2, lemon: 5 }],
  ['vermicelli-upma', 'Vermicelli Upma', 'B', 20, 'south', { vermicelli: 60, onion: 20, green_peas: 15, carrot: 20, oil: 7, mustard_seeds: 1 }],
  ['bread-omelette', 'Bread Omelette', 'B', 10, 'street', { bread_ww: 60, egg: 100, onion: 20, butter: 5, tomato: 20 }],
  ['masala-omelette', 'Masala Omelette (3 eggs)', 'BD', 10, 'street', { egg: 150, onion: 30, tomato: 30, green_chilli: 3, coriander: 3, oil: 5 }],
  ['egg-bhurji-pav', 'Egg Bhurji Pav', 'BD', 15, 'street', { egg: 120, onion: 30, tomato: 30, butter: 7, bread_white: 60, green_chilli: 2 }],
  ['boiled-eggs-toast', 'Boiled Eggs on Toast', 'B', 10, 'modern', { egg: 100, bread_ww: 60, butter: 5 }],
  ['egg-white-omelette', 'Egg White Veggie Omelette', 'B', 10, 'modern', { egg_white: 180, spinach: 40, onion: 20, capsicum: 30, oil: 4, bread_ww: 30 }],
  ['namkeen-dalia', 'Vegetable Dalia with Moong', 'BD', 25, 'north', { dalia: 50, moong_dal: 20, carrot: 20, green_peas: 20, ghee: 5, onion: 15 }],
  ['sweet-dalia', 'Sweet Dalia', 'B', 20, 'north', { dalia: 50, milk: 200, jaggery: 10, almonds: 6 }],
  ['misal-pav', 'Misal Pav', 'BL', 35, 'west', { moong_sprouts: 100, onion: 30, tomato: 30, oil: 8, bread_white: 60, murmura: 10, garam_masala: 2 }],
  ['sprouts-salad', 'Moong Sprouts Salad', 'BS', 10, 'modern', { moong_sprouts: 120, onion: 25, tomato: 30, cucumber: 30, lemon: 5, coriander: 3, roasted_peanuts: 10 }],
  ['paneer-bhurji-toast', 'Paneer Bhurji on Toast', 'BD', 15, 'north', { paneer: 80, onion: 25, tomato: 30, butter: 5, bread_ww: 60, turmeric: 1 }],
  ['tofu-bhurji', 'Tofu Bhurji with Toast', 'BD', 15, 'modern', { tofu: 120, onion: 25, tomato: 30, capsicum: 25, oil: 6, turmeric: 1, bread_ww: 40 }],
  ['cornflakes-milk', 'Corn Flakes with Milk & Banana', 'B', 5, 'modern', { corn_flakes: 40, milk: 200, banana: 60 }],
  ['pb-banana-toast', 'Peanut Butter Banana Toast', 'BS', 5, 'modern', { bread_ww: 60, peanut_butter: 20, banana: 80 }],
  ['yogurt-bowl', 'Hung Curd Bowl with Pomegranate & Walnuts', 'BS', 5, 'modern', { greek_yogurt: 170, oats: 25, jaggery: 8, pomegranate: 40, walnuts: 10 }],
  ['kuttu-cheela', 'Kuttu Cheela', 'B', 15, 'north', { kuttu: 60, curd: 30, ghee: 6, green_chilli: 2 }],
  ['rajgira-porridge', 'Rajgira Porridge', 'B', 15, 'west', { rajgira: 50, milk: 200, jaggery: 8 }],
  ['thalipeeth', 'Thalipeeth', 'B', 25, 'west', { jowar: 30, bajra: 20, besan: 15, onion: 25, oil: 8, sesame: 3 }],
  ['aloo-puri', 'Aloo Puri', 'BL', 30, 'north', { atta: 60, oil: 20, potato: 100, tomato: 30 }],
  ['chole-bhature', 'Chole Bhature', 'LB', 45, 'north', { maida: 70, oil: 20, kabuli_chana: 60, onion: 30, tomato: 40, garam_masala: 2 }],
  ['whey-banana-shake', 'Whey Banana Shake', 'BS', 5, 'modern', { whey: 30, milk: 250, banana: 100, peanut_butter: 10 }],
  ['soy-smoothie', 'Soy Milk Oat Smoothie', 'BS', 5, 'modern', { soymilk: 250, banana: 100, oats: 20, chia: 5 }],

  // ---------------------------------------------------------------- lunch / dinner
  ['dal-chawal', 'Dal Chawal', 'LD', 30, 'north', { toor_dal: 45, rice_cooked: 200, ghee: 5, tomato: 20, onion: 15, turmeric: 1, cumin: 1 }],
  ['dal-tadka-roti', 'Dal Tadka with Roti', 'LD', 30, 'north', { toor_dal: 45, atta: 60, oil: 7, onion: 20, tomato: 25, garlic: 4 }],
  ['jain-dal-roti', 'Jain Dal with Roti', 'LD', 30, 'west', { toor_dal: 45, atta: 60, ghee: 7, tomato: 30, cumin: 1, turmeric: 1 }],
  ['moong-khichdi', 'Moong Dal Khichdi with Curd', 'LD', 25, 'north', { rice_raw: 50, moong_dal: 40, ghee: 7, cumin: 1, turmeric: 1, curd: 100 }],
  ['masoor-dal-rice', 'Masoor Dal with Rice', 'LD', 25, 'east', { masoor_dal: 45, rice_cooked: 200, onion: 20, tomato: 25, oil: 6 }],
  ['rajma-chawal', 'Rajma Chawal', 'L', 45, 'north', { rajma: 60, rice_cooked: 200, onion: 30, tomato: 50, oil: 8, ginger: 3, garlic: 3 }],
  ['chole-rice', 'Chole Rice', 'L', 40, 'north', { kabuli_chana: 60, rice_cooked: 180, onion: 30, tomato: 50, oil: 8 }],
  ['chana-masala-roti', 'Chana Masala with Roti', 'LD', 40, 'north', { kabuli_chana: 60, atta: 60, onion: 30, tomato: 40, oil: 8 }],
  ['kadhi-chawal', 'Kadhi Chawal', 'L', 35, 'north', { besan: 25, curd: 150, rice_cooked: 180, oil: 6, onion: 20, fenugreek_seeds: 1 }],
  ['sambar-rice', 'Sambar Rice', 'LD', 35, 'south', { toor_dal: 40, rice_cooked: 200, drumstick: 30, pumpkin: 30, tomato: 30, tamarind: 6, oil: 6, onion: 20 }],
  ['rasam-rice', 'Rasam Rice', 'LD', 25, 'south', { toor_dal: 20, rice_cooked: 200, tomato: 60, tamarind: 6, ghee: 5, black_pepper: 1, garlic: 3 }],
  ['curd-rice', 'Curd Rice', 'LD', 10, 'south', { rice_cooked: 180, curd: 150, mustard_seeds: 1, green_chilli: 2, oil: 3, pomegranate: 20 }],
  ['lemon-rice', 'Lemon Rice', 'L', 15, 'south', { rice_cooked: 200, roasted_peanuts: 15, oil: 8, lemon: 10, turmeric: 1, chana_dal: 5, mustard_seeds: 1 }],
  ['bisi-bele-bath', 'Bisi Bele Bath', 'LD', 40, 'south', { rice_raw: 50, toor_dal: 30, carrot: 25, beans: 25, green_peas: 15, tamarind: 5, ghee: 8 }],
  ['veg-pulao-raita', 'Veg Pulao with Raita', 'LD', 30, 'north', { rice_raw: 70, green_peas: 25, carrot: 25, beans: 25, onion: 20, ghee: 7, curd: 100 }],
  ['veg-biryani', 'Vegetable Biryani', 'LD', 50, 'south', { rice_raw: 75, potato: 40, carrot: 25, beans: 25, green_peas: 15, onion: 40, curd: 40, ghee: 10 }],
  ['chicken-biryani', 'Chicken Biryani', 'LD', 60, 'south', { rice_raw: 75, chicken_thigh: 120, onion: 40, curd: 40, tomato: 25, ghee: 10, garam_masala: 2 }],
  ['mutton-biryani', 'Mutton Biryani', 'LD', 90, 'south', { rice_raw: 75, mutton: 110, onion: 40, curd: 40, ghee: 12 }],
  ['egg-biryani', 'Egg Biryani', 'LD', 45, 'south', { rice_raw: 75, egg: 100, onion: 40, curd: 30, tomato: 25, oil: 10 }],
  ['chicken-curry-rice', 'Chicken Curry with Rice', 'LD', 45, 'north', { chicken_thigh: 150, rice_cooked: 180, onion: 50, tomato: 50, oil: 10, ginger: 4, garlic: 4, garam_masala: 2 }],
  ['chicken-curry-roti', 'Chicken Curry with Roti', 'LD', 45, 'north', { chicken_thigh: 150, atta: 60, onion: 50, tomato: 50, oil: 10, garlic: 4 }],
  ['butter-chicken-naan', 'Butter Chicken with Naan', 'DL', 50, 'north', { chicken_thigh: 140, butter: 12, cream: 20, tomato_puree: 80, maida: 70, curd: 15 }],
  ['tandoori-chicken-salad', 'Tandoori Chicken with Salad', 'LD', 40, 'north', { chicken_breast: 180, curd: 40, lemon: 5, onion: 30, cucumber: 60, oil: 4, chili_powder: 2 }],
  ['grilled-chicken-brown-rice', 'Grilled Chicken, Brown Rice & Broccoli', 'LD', 30, 'modern', { chicken_breast: 150, brown_rice_cooked: 180, broccoli: 80, oil: 5 }],
  ['chicken-tikka-roti', 'Chicken Tikka with Roti', 'LD', 40, 'north', { chicken_breast: 150, curd: 40, capsicum: 40, onion: 30, atta: 60, oil: 5 }],
  ['chicken-stir-fry-rice', 'Chicken Stir-fry with Rice', 'LD', 25, 'indo-chinese', { chicken_breast: 130, rice_cooked: 180, capsicum: 50, cabbage: 50, carrot: 30, soy_sauce: 10, oil: 8 }],
  ['chicken-keema-roti', 'Chicken Keema Matar with Roti', 'LD', 35, 'north', { chicken_breast: 130, green_peas: 40, onion: 40, tomato: 40, oil: 8, atta: 60 }],
  ['mutton-curry-rice', 'Mutton Curry with Rice', 'LD', 75, 'north', { mutton: 130, rice_cooked: 180, onion: 50, tomato: 40, oil: 10, curd: 20 }],
  ['keema-pav', 'Keema Pav', 'LD', 40, 'west', { keema: 110, green_peas: 40, onion: 40, tomato: 40, oil: 6, bread_white: 60 }],
  ['fish-curry-rice', 'Bengali Fish Curry with Rice', 'LD', 35, 'east', { fish_rohu: 150, rice_cooked: 200, onion: 30, tomato: 40, mustard_oil: 10, turmeric: 1 }],
  ['grilled-pomfret', 'Grilled Pomfret with Veg & Rice', 'LD', 30, 'west', { fish_pomfret: 170, lemon: 5, oil: 5, beans: 80, carrot: 50, rice_cooked: 120 }],
  ['kerala-fish-curry', 'Kerala Mackerel Curry with Rice', 'LD', 40, 'south', { fish_mackerel: 150, coconut_milk: 60, tamarind: 5, coconut_oil: 8, onion: 30, rice_cooked: 180 }],
  ['prawn-masala-rice', 'Prawn Masala with Rice', 'LD', 35, 'west', { prawns: 150, onion: 40, tomato: 50, oil: 10, coconut: 15, rice_cooked: 180 }],
  ['tuna-wrap', 'Tuna Salad Wrap', 'LD', 15, 'modern', { tuna: 100, atta: 50, lettuce: 30, onion: 20, tomato: 30, curd: 30 }],
  ['egg-curry-rice', 'Egg Curry with Rice', 'LD', 30, 'north', { egg: 150, onion: 40, tomato: 50, oil: 10, rice_cooked: 180 }],
  ['egg-curry-roti', 'Egg Curry with Roti', 'LD', 30, 'north', { egg: 150, onion: 40, tomato: 50, oil: 10, atta: 60 }],
  ['palak-paneer-roti', 'Palak Paneer with Roti', 'LD', 35, 'north', { paneer: 100, spinach: 150, onion: 30, tomato: 20, oil: 8, atta: 60, cream: 10 }],
  ['paneer-butter-masala-roti', 'Paneer Butter Masala with Roti', 'LD', 35, 'north', { paneer: 100, tomato_puree: 80, butter: 10, cream: 15, cashews: 8, atta: 60 }],
  ['kadai-paneer-rice', 'Kadai Paneer with Rice', 'LD', 35, 'north', { paneer: 100, capsicum: 60, onion: 40, tomato: 50, oil: 10, rice_cooked: 150 }],
  ['matar-paneer-roti', 'Matar Paneer with Roti', 'LD', 35, 'north', { paneer: 80, green_peas: 60, onion: 30, tomato: 50, oil: 8, atta: 60 }],
  ['paneer-tikka-salad', 'Paneer Tikka with Salad', 'LDS', 30, 'north', { paneer: 120, curd: 30, capsicum: 50, onion: 30, cucumber: 60, lemon: 5 }],
  ['jain-paneer-capsicum', 'Jain Paneer Capsicum with Roti', 'LD', 30, 'west', { paneer: 100, capsicum: 70, tomato: 60, ghee: 8, atta: 60, cumin: 1 }],
  ['aloo-gobi-roti', 'Aloo Gobi with Roti', 'LD', 30, 'north', { potato: 100, cauliflower: 120, oil: 10, tomato: 30, atta: 60 }],
  ['bhindi-masala-roti', 'Bhindi Masala with Roti', 'LD', 30, 'north', { okra: 150, onion: 40, tomato: 30, oil: 10, atta: 60 }],
  ['baingan-bharta-roti', 'Baingan Bharta with Roti', 'LD', 40, 'north', { brinjal: 200, onion: 40, tomato: 50, oil: 10, atta: 60 }],
  ['mixed-veg-roti', 'Mixed Veg Sabzi with Roti', 'LD', 30, 'north', { carrot: 40, beans: 40, green_peas: 40, cauliflower: 60, oil: 10, atta: 60, tomato: 30 }],
  ['lauki-chana-dal', 'Lauki Chana Dal with Roti', 'LD', 35, 'north', { lauki: 150, chana_dal: 35, tomato: 30, oil: 7, atta: 60 }],
  ['jain-lauki-roti', 'Jain Lauki Sabzi with Roti', 'LD', 25, 'west', { lauki: 200, tomato: 40, ghee: 7, atta: 60, cumin: 1 }],
  ['karela-roti', 'Karela Sabzi with Roti', 'LD', 30, 'north', { karela: 150, onion: 40, oil: 10, atta: 60, besan: 10 }],
  ['sarson-saag-makki', 'Sarson ka Saag with Makki Roti', 'LD', 60, 'north', { sarson: 200, spinach: 80, corn_flour: 70, ghee: 10, garlic: 4, onion: 20 }],
  ['aloo-methi-roti', 'Aloo Methi with Roti', 'LD', 25, 'north', { potato: 100, methi: 80, oil: 8, atta: 60 }],
  ['soya-curry-rice', 'Soya Chunk Curry with Rice', 'LD', 30, 'north', { soya_chunks: 50, onion: 40, tomato: 50, oil: 8, rice_cooked: 180 }],
  ['soya-pulao', 'Soya Chunk Pulao', 'LD', 30, 'north', { soya_chunks: 40, rice_raw: 70, green_peas: 25, carrot: 25, onion: 25, oil: 8 }],
  ['tofu-stir-fry', 'Tofu Stir-fry with Brown Rice', 'LD', 25, 'indo-chinese', { tofu: 150, capsicum: 50, broccoli: 60, soy_sauce: 10, oil: 8, brown_rice_cooked: 150, garlic: 4 }],
  ['tofu-palak-roti', 'Tofu Palak with Roti', 'LD', 30, 'modern', { tofu: 150, spinach: 150, tomato: 30, oil: 8, atta: 60 }],
  ['rajma-bowl', 'Rajma Brown Rice Bowl', 'L', 40, 'modern', { rajma: 50, brown_rice_cooked: 150, onion: 25, tomato: 40, lettuce: 30, curd: 50 }],
  ['chickpea-quinoa-salad', 'Chickpea Quinoa Salad', 'LD', 15, 'modern', { kabuli_chana: 60, cucumber: 60, tomato: 50, onion: 25, lemon: 8, oil: 5, quinoa_cooked: 100 }],
  ['quinoa-pulao', 'Quinoa Veg Pulao', 'LD', 25, 'modern', { quinoa_cooked: 180, green_peas: 30, carrot: 30, beans: 30, oil: 6, roasted_peanuts: 10 }],
  ['sprout-curry-roti', 'Moong Sprout Curry with Roti', 'LD', 25, 'west', { moong_sprouts: 150, onion: 30, tomato: 40, oil: 7, atta: 60 }],
  ['lobia-rice', 'Lobia Curry with Rice', 'LD', 40, 'north', { lobia: 60, onion: 30, tomato: 50, oil: 8, rice_cooked: 180 }],
  ['dal-makhani-rice', 'Dal Makhani with Rice', 'LD', 60, 'north', { urad_dal: 45, rajma: 15, butter: 10, cream: 15, tomato_puree: 60, rice_cooked: 150 }],
  ['dal-palak-roti', 'Dal Palak with Roti', 'LD', 30, 'north', { toor_dal: 40, spinach: 100, tomato: 30, garlic: 4, oil: 6, atta: 60 }],
  ['bajra-roti-dal', 'Bajra Roti with Moong Dal', 'LD', 30, 'west', { bajra: 70, moong_dal: 40, ghee: 7, tomato: 25, onion: 15 }],
  ['jowar-roti-sabzi', 'Jowar Roti with Beans Sabzi', 'LD', 30, 'west', { jowar: 70, beans: 80, carrot: 40, oil: 7, besan: 10 }],
  ['ragi-mudde-saaru', 'Ragi Mudde with Saaru', 'LD', 30, 'south', { ragi: 80, toor_dal: 30, tomato: 40, tamarind: 5, ghee: 5 }],
  ['avial-rice', 'Avial with Rice', 'LD', 40, 'south', { carrot: 40, beans: 40, drumstick: 30, pumpkin: 40, yam: 30, coconut: 30, curd: 40, coconut_oil: 7, rice_cooked: 180 }],
  ['veg-kurma-chapati', 'Veg Kurma with Chapati', 'DL', 35, 'south', { carrot: 30, beans: 30, green_peas: 30, potato: 50, coconut: 25, cashews: 5, oil: 8, atta: 60 }],
  ['jackfruit-curry-rice', 'Raw Jackfruit Curry with Rice', 'LD', 45, 'south', { jackfruit: 150, onion: 30, coconut: 20, oil: 8, rice_cooked: 180 }],
  ['arbi-masala-roti', 'Arbi Masala with Roti', 'LD', 35, 'north', { arbi: 150, oil: 10, atta: 60, tomato: 20 }],
  ['jain-pumpkin-roti', 'Jain Pumpkin Sabzi with Roti', 'LD', 25, 'west', { pumpkin: 200, jaggery: 5, oil: 7, atta: 60, fenugreek_seeds: 1 }],
  ['cabbage-poriyal-rice', 'Cabbage Poriyal, Dal & Rice', 'LD', 30, 'south', { cabbage: 150, coconut: 20, oil: 7, urad_dal: 5, rice_cooked: 180, toor_dal: 30 }],
  ['beans-poriyal-rice', 'Beans Poriyal, Moong Dal & Rice', 'LD', 30, 'south', { beans: 150, coconut: 20, oil: 7, rice_cooked: 180, moong_dal: 30 }],
  ['egg-fried-rice', 'Egg Fried Rice', 'LD', 20, 'indo-chinese', { rice_cooked: 200, egg: 100, cabbage: 40, carrot: 30, capsicum: 30, soy_sauce: 8, oil: 10 }],
  ['veg-hakka-noodles', 'Veg Hakka Noodles', 'LD', 20, 'indo-chinese', { rice_noodles: 70, cabbage: 60, capsicum: 40, carrot: 30, soy_sauce: 10, oil: 10 }],
  ['chicken-noodles', 'Chicken Hakka Noodles', 'LD', 25, 'indo-chinese', { rice_noodles: 70, chicken_breast: 100, cabbage: 50, capsicum: 40, soy_sauce: 10, oil: 10 }],
  ['veg-pasta', 'Tomato Veg Pasta', 'LD', 25, 'modern', { pasta: 80, tomato_puree: 80, capsicum: 40, mushroom: 40, oil: 8, cheese: 15 }],
  ['chicken-pasta', 'Chicken Tomato Pasta', 'LD', 25, 'modern', { pasta: 80, chicken_breast: 100, tomato_puree: 80, oil: 8, broccoli: 50 }],
  ['mushroom-matar-roti', 'Mushroom Matar with Roti', 'LD', 30, 'north', { mushroom: 120, green_peas: 60, onion: 30, tomato: 40, oil: 8, atta: 60 }],
  ['paneer-wrap', 'Paneer Kathi Wrap', 'LDS', 20, 'street', { paneer: 80, atta: 60, onion: 25, capsicum: 30, curd: 20, lettuce: 20 }],
  ['chicken-wrap', 'Chicken Kathi Wrap', 'LD', 20, 'street', { chicken_breast: 120, atta: 60, onion: 25, lettuce: 30, curd: 30 }],
  ['egg-roll', 'Kolkata Egg Roll', 'SD', 15, 'street', { egg: 100, maida: 60, onion: 30, oil: 10, ketchup: 10 }],
  ['veg-thali', 'Veg Thali (dal, sabzi, rice, roti, curd)', 'L', 45, 'north', { toor_dal: 35, rice_cooked: 120, atta: 40, beans: 60, curd: 80, ghee: 6, tomato: 20 }],
  ['paneer-quinoa-bowl', 'Grilled Paneer Quinoa Bowl', 'LD', 25, 'modern', { paneer: 100, quinoa_cooked: 150, capsicum: 50, broccoli: 50, oil: 5 }],
  ['besan-gatte-roti', 'Besan Gatte with Roti', 'LD', 45, 'west', { besan: 50, curd: 80, oil: 10, atta: 50 }],
  ['dal-dhokli', 'Dal Dhokli', 'LD', 40, 'west', { toor_dal: 40, atta: 50, jaggery: 8, tamarind: 5, peanuts: 10, ghee: 6 }],
  ['methi-dal-rice', 'Methi Dal with Rice', 'LD', 30, 'west', { toor_dal: 40, methi: 60, rice_cooked: 180, oil: 6, garlic: 3 }],
  ['khichdi-kadhi', 'Khichdi with Kadhi', 'D', 35, 'west', { rice_raw: 45, moong_dal: 35, ghee: 6, besan: 15, curd: 100 }],
  ['jowar-khichdi', 'Jowar Vegetable Khichdi', 'D', 35, 'west', { jowar: 50, moong_dal: 35, carrot: 30, green_peas: 20, ghee: 6 }],
  ['chicken-soup-toast', 'Chicken Clear Soup with Toast', 'D', 30, 'modern', { chicken_breast: 120, carrot: 40, cabbage: 50, onion: 20, black_pepper: 1, bread_ww: 30 }],
  ['tomato-soup-paneer', 'Tomato Soup with Paneer Cubes', 'D', 25, 'modern', { tomato: 150, carrot: 40, paneer: 60, butter: 5, bread_ww: 30 }],
  ['lentil-soup-salad', 'Masoor Lentil Soup with Salad', 'D', 25, 'modern', { masoor_dal: 50, carrot: 30, onion: 20, tomato: 40, cucumber: 60, lemon: 5, oil: 5 }],
  ['grilled-fish-salad', 'Grilled Fish with Salad', 'D', 25, 'modern', { fish_rohu: 170, lettuce: 60, cucumber: 60, tomato: 50, oil: 6, lemon: 5 }],
  ['tofu-tikka', 'Tofu Tikka', 'SD', 25, 'modern', { tofu: 150, capsicum: 40, onion: 30, lemon: 5, oil: 5 }],

  // ---------------------------------------------------------------- snacks
  ['roasted-chana', 'Roasted Chana', 'S', 2, 'street', { chana_dal: 40 }],
  ['masala-peanuts', 'Masala Peanuts', 'S', 2, 'street', { roasted_peanuts: 30 }],
  ['fruit-bowl', 'Seasonal Fruit Bowl', 'SB', 5, 'modern', { apple: 100, papaya: 100, banana: 60, pomegranate: 40 }],
  ['banana-almonds', 'Banana with Almonds', 'S', 1, 'modern', { banana: 120, almonds: 15 }],
  ['apple-pb', 'Apple with Peanut Butter', 'S', 2, 'modern', { apple: 150, peanut_butter: 15 }],
  ['dhokla', 'Khaman Dhokla', 'SB', 30, 'west', { besan: 60, curd: 30, oil: 5, mustard_seeds: 1, sugar: 5 }],
  ['sprouts-chaat', 'Sprouts Chaat', 'S', 10, 'street', { moong_sprouts: 100, onion: 20, tomato: 25, pomegranate: 20, lemon: 5 }],
  ['bhel-puri', 'Bhel Puri', 'S', 10, 'street', { murmura: 30, roasted_peanuts: 10, onion: 25, tomato: 25, potato: 30, tamarind: 5, coriander: 3 }],
  ['chaas', 'Masala Chaas', 'S', 3, 'west', { buttermilk: 300, cumin: 1, coriander: 2 }],
  ['mango-lassi', 'Mango Lassi', 'S', 5, 'north', { curd: 200, mango: 80, sugar: 8 }],
  ['boiled-eggs', 'Boiled Eggs (2)', 'S', 10, 'modern', { egg: 100, black_pepper: 0.5 }],
  ['yogurt-berries', 'Greek Yogurt with Berries & Honey', 'S', 3, 'modern', { greek_yogurt: 170, strawberries: 80, honey: 8 }],
  ['whey-shake', 'Whey Protein with Banana', 'S', 2, 'modern', { whey: 30, banana: 60 }],
  ['veg-sandwich', 'Veg Cheese Sandwich', 'SB', 10, 'street', { bread_ww: 60, cucumber: 40, tomato: 40, onion: 20, butter: 7, cheese: 15 }],
  ['spinach-corn-sandwich', 'Spinach Corn Sandwich', 'SB', 15, 'modern', { bread_ww: 60, spinach: 50, sweet_corn: 40, cheese: 15, butter: 5 }],
  ['corn-chaat', 'Butter Corn Chaat', 'S', 10, 'street', { sweet_corn: 120, lemon: 5, butter: 5, chili_powder: 1 }],
  ['dry-fruit-mix', 'Dry Fruit & Nut Mix', 'S', 1, 'modern', { almonds: 10, walnuts: 10, cashews: 10, raisins: 10, dates: 20 }],
  ['popcorn', 'Butter Popcorn', 'S', 5, 'modern', { popcorn: 30, butter: 5 }],
  ['coconut-water-almonds', 'Coconut Water with Almonds', 'S', 1, 'south', { coconut_water: 250, almonds: 12 }],
  ['sweet-potato-chaat', 'Sweet Potato Chaat', 'S', 20, 'street', { sweet_potato: 150, lemon: 5, chili_powder: 1 }],
  ['peanut-chikki', 'Peanut Chikki', 'S', 1, 'west', { roasted_peanuts: 25, jaggery: 20 }],
  ['masala-chai', 'Masala Chai', 'SB', 5, 'north', { tea: 150, milk: 80, sugar: 8 }],
  ['filter-coffee', 'Filter Coffee', 'SB', 5, 'south', { coffee: 100, milk: 100, sugar: 6 }],
  ['hummus-veg-sticks', 'Hummus with Veg Sticks', 'S', 10, 'modern', { kabuli_chana: 50, sesame: 10, oil: 7, lemon: 5, carrot: 60, cucumber: 60 }],
  ['egg-white-sandwich', 'Egg White Sandwich', 'SB', 10, 'modern', { egg_white: 120, bread_ww: 60, lettuce: 20, tomato: 30 }],
  ['guava-orange', 'Guava & Orange', 'S', 2, 'modern', { guava: 100, orange: 130 }],
  ['kheer', 'Rice Kheer', 'SD', 30, 'north', { milk: 200, rice_raw: 20, sugar: 15, cardamom: 1, almonds: 5 }],
  ['besan-ladoo', 'Besan Ladoo', 'S', 30, 'north', { besan: 30, ghee: 15, sugar: 15 }],
  ['roasted-peanut-chaat', 'Peanut Chaat', 'S', 5, 'street', { roasted_peanuts: 30, onion: 20, tomato: 25, lemon: 5, coriander: 3 }],
  ['paneer-cubes', 'Paneer Cubes with Pepper', 'S', 5, 'modern', { paneer: 80, black_pepper: 0.5 }],
  ['tofu-cubes', 'Pan-seared Tofu Cubes', 'S', 10, 'modern', { tofu: 120, oil: 3, black_pepper: 0.5 }],
  ['soy-milk-glass', 'Glass of Soy Milk with Dates', 'S', 1, 'modern', { soymilk: 250, dates: 20 }],
  ['milk-glass', 'Glass of Milk with Dates', 'S', 1, 'north', { milk: 250, dates: 20 }],
  ['papaya-chia', 'Papaya with Chia Seeds', 'SB', 3, 'modern', { papaya: 200, chia: 8 }],
  ['pumpkin-seed-trail', 'Seed Trail Mix', 'S', 1, 'modern', { pumpkin_seeds: 15, sunflower_seeds: 10, raisins: 10, roasted_peanuts: 10 }],
  ['watermelon-bowl', 'Watermelon & Muskmelon Bowl', 'S', 3, 'modern', { watermelon: 200, muskmelon: 150 }],
  ['chikoo-milkshake', 'Chikoo Milkshake', 'S', 5, 'west', { chikoo: 120, milk: 200, sugar: 5 }],
  ['figs-walnuts', 'Anjeer & Walnuts', 'S', 1, 'modern', { figs_dried: 25, walnuts: 15 }],
  ['moong-dal-soup', 'Moong Dal Soup', 'SD', 20, 'modern', { moong_dal: 40, tomato: 40, ghee: 3, cumin: 1, black_pepper: 0.5 }],
];
