#!/usr/bin/env node
// Copies self-hosted third-party assets into public/ and (with --media)
// re-encodes the background videos. Outputs are committed, so a deploy needs
// no network access and the CSP can stay `script-src 'self'`.
//
//   npm run assets            fonts + vendor JS/CSS
//   npm run assets -- --media also transcode video (ffmpeg-static; ~1-2 min)
//
// Fonts:  Poppins (SIL OFL 1.1) from @fontsource/poppins, latin subset.
// Vendor: Leaflet (BSD-2-Clause), Chart.js (MIT).
// Media:  public/media/ smoke-{wide,tall}.{webm,mp4,jpg,webp}, coach.{webm,mp4,jpg,webp},
//         media.json (durations + brightest-frame timestamps for the contrast test).
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const NM = path.join(ROOT, 'node_modules');
const args = new Set(process.argv.slice(2));

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  return path.relative(ROOT, to);
}

function fonts() {
  const out = [];
  for (const w of [300, 400, 500, 600, 700]) {
    const file = `poppins-latin-${w}-normal.woff2`;
    out.push(copy(path.join(NM, '@fontsource/poppins/files', file), path.join(PUBLIC, 'fonts', file)));
  }
  copy(path.join(NM, '@fontsource/poppins/LICENSE'), path.join(PUBLIC, 'fonts', 'LICENSE-Poppins-OFL.txt'));
  return out;
}

function vendor() {
  const out = [];
  const L = path.join(NM, 'leaflet/dist');
  out.push(copy(path.join(L, 'leaflet.js'), path.join(PUBLIC, 'vendor/leaflet/leaflet.js')));
  out.push(copy(path.join(L, 'leaflet.css'), path.join(PUBLIC, 'vendor/leaflet/leaflet.css')));
  for (const img of fs.readdirSync(path.join(L, 'images'))) {
    copy(path.join(L, 'images', img), path.join(PUBLIC, 'vendor/leaflet/images', img));
  }
  copy(path.join(NM, 'leaflet/LICENSE'), path.join(PUBLIC, 'vendor/leaflet/LICENSE'));
  out.push(copy(path.join(NM, 'chart.js/dist/chart.umd.min.js'), path.join(PUBLIC, 'vendor/chart.umd.min.js')));
  copy(path.join(NM, 'chart.js/LICENSE.md'), path.join(PUBLIC, 'vendor/LICENSE-chartjs.md'));
  return out;
}

// ---------------------------------------------------------------- media
const FFMPEG = () => require('ffmpeg-static');

function ff(argv, { capture = false } = {}) {
  const res = spawnSync(FFMPEG(), ['-hide_banner', '-loglevel', capture ? 'info' : 'error', '-y', ...argv], {
    encoding: 'utf8', maxBuffer: 64 * 1024 * 1024,
  });
  if (res.status !== 0) throw new Error(`ffmpeg failed: ${res.stderr.slice(-2000)}`);
  return res.stderr;
}

// Mean luma per frame (signalstats YAVG) -> [{ t, y }].
function lumaTrack(file) {
  const log = ff(['-i', file, '-vf', 'signalstats,metadata=print:key=lavfi.signalstats.YAVG', '-f', 'null', '-'], { capture: true });
  const out = [];
  let t = null;
  for (const line of log.split(/\r?\n/)) {
    const pts = line.match(/pts_time:([\d.]+)/);
    if (pts) t = Number(pts[1]);
    const y = line.match(/lavfi\.signalstats\.YAVG=([\d.]+)/);
    if (y && t !== null) out.push({ t, y: Number(y[1]) });
  }
  return out;
}

function encode(src, name, vf) {
  const dir = path.join(PUBLIC, 'media');
  fs.mkdirSync(dir, { recursive: true });
  const base = path.join(dir, name);
  // H.264 MP4 for Safari/Edge; VP9 WebM is smaller where supported. No audio.
  ff(['-i', src, '-vf', vf, '-an', '-c:v', 'libx264', '-preset', 'slow', '-crf', '30', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', `${base}.mp4`]);
  ff(['-i', src, '-vf', vf, '-an', '-c:v', 'libvpx-vp9', '-crf', '40', '-b:v', '0', '-row-mt', '1', '-deadline', 'good', '-cpu-used', '2', `${base}.webm`]);
  // Poster = first frame (what reduced-motion / slow-network visitors see, and
  // what the frozen visual tests show).
  ff(['-i', `${base}.mp4`, '-frames:v', '1', '-q:v', '3', `${base}.jpg`]);
  ff(['-i', `${base}.mp4`, '-frames:v', '1', '-c:v', 'libwebp', '-quality', '78', `${base}.webp`]);
  const track = lumaTrack(`${base}.mp4`);
  const brightest = track.reduce((a, b) => (b.y > a.y ? b : a), track[0]);
  const size = ext => fs.statSync(`${base}.${ext}`).size;
  return {
    duration: track.length ? track[track.length - 1].t : null,
    brightest: { time: brightest.t, meanLuma: Math.round(brightest.y * 10) / 10 },
    bytes: { mp4: size('mp4'), webm: size('webm'), jpg: size('jpg'), webp: size('webp') },
  };
}

function media() {
  const smoke = path.join(PUBLIC, 'backgroundhome.mp4');
  const coach = path.join(PUBLIC, 'trainertrainee1.mp4');
  for (const f of [smoke, coach]) if (!fs.existsSync(f)) throw new Error(`missing source video ${f}`);
  const manifest = {
    _note: 'Generated by scripts/build-assets.js --media. Sources: public/backgroundhome.mp4 (portrait 1440x2732), public/trainertrainee1.mp4.',
    // Wide: the middle 1440x1080 band of the portrait source (what a desktop
    // viewport showed with object-fit: cover), at 1280x960.
    'smoke-wide': encode(smoke, 'smoke-wide', 'crop=1440:1080:0:(ih-1080)/2,scale=1280:960,fps=25'),
    // Tall: the whole portrait source for phones, at 720 wide.
    'smoke-tall': encode(smoke, 'smoke-tall', 'scale=720:-2,fps=25'),
    coach: encode(coach, 'coach', 'scale=1280:-2,fps=25'),
  };
  fs.writeFileSync(path.join(PUBLIC, 'media', 'media.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return manifest;
}

// Brightest frame of each background variant, for the contrast test
// (tests/e2e/contrast.spec.js renders every page on top of it).
function brightFrames() {
  const manifest = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'media', 'media.json'), 'utf8'));
  const dir = path.join(ROOT, 'tests', 'fixtures', 'media');
  fs.mkdirSync(dir, { recursive: true });
  for (const v of ['smoke-wide', 'smoke-tall', 'coach']) {
    const t = manifest[v].brightest.time;
    ff(['-ss', String(t), '-i', path.join(PUBLIC, 'media', `${v}.mp4`), '-frames:v', '1', '-q:v', '2', path.join(dir, `${v}-brightest.jpg`)]);
  }
  return dir;
}

const done = [...fonts(), ...vendor()];
console.log(`✔ copied ${done.length} font/vendor files`);
if (args.has('--media')) {
  const t0 = Date.now();
  const m = media();
  for (const [k, v] of Object.entries(m)) {
    if (k.startsWith('_')) continue;
    const kb = n => `${Math.round(n / 1024)} KB`;
    console.log(`✔ ${k}: mp4 ${kb(v.bytes.mp4)}, webm ${kb(v.bytes.webm)}, poster ${kb(v.bytes.webp)} webp; brightest frame at ${v.brightest.time}s (mean luma ${v.brightest.meanLuma})`);
  }
  console.log(`  media built in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
if (args.has('--media') || args.has('--bright')) {
  console.log(`✔ brightest frames -> ${path.relative(ROOT, brightFrames())}`);
}
